name: CICD using Maven and Tomcat
on:
  push: # run where there is commit to repo
  workflow_dispatch:  $ run manually
jobs:
  CICDjob:
    runs-on:  ubuntu-latest
    steps:
      - name: Clone the repo on ubuntu server
        uses: actions/checkout@v4
      - name: Install Java and Maven on ubuntu server
        uses: actions/setup-jave@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache:  'maven'
      - name: Build a code
        run:  mvn package
